### ISSUE TITLE
Questions: Timeline pagination, local storage

### ISSUE THREAD

**Issue by pwFoo** [Zatnosk/libodonjs#5]
Hi @Zatnosk,

I played with the mastodon api and searching for a working lib to simplify it. I checked the source code and it looks like libodonjs handles 
* app register, auth, token with locale storage to reuse?
* wrap functions around api endpoints

Missing features
* write a new toot?

During my own api tests I searched for timeline pagination and haven't found an example. Do you know how to build a timeline pagination 
1. show initial count of posts (for example 10 = 1-10)
2. load (10) older posts (11-20)

I found since_id, max_id and limit, but don't know how to build the correct query to get the exact posts / toots needed...

**Comment by Zatnosk** [comment]
Yes, posting toots is still unimplemented in libodon.js. It shouldn't be too much work to implement it, but I haven't had the time or motivation to finish it (mostly because it seems noone is using this lib, which is difficult when it's incomplete - bad circle that is.)

Timeline pagination should happen automatically on the Mastodon end, you can choose how many posts to show per page with the "limit" option. E.g. `app.timeline("home", {limit: 10})`. The default limit is 20.

Additionally, when you make a request to the timeline, there should be a max_id and/or since_id included in the response, which you can use to get the next/previous page. E.g. `app.timeline("home",{limit: 10, max_id: 1234567890})`.

I hope this helps :)

**Comment by pwFoo** [comment]
Yes and that toot
https://mastodon.social/@Gargron/100846335353411164
